language: php

php:
  - 7.4

services:
  - mysql

before_script:
    - composer update
    - cp .env.example .env
    - mysql -e 'CREATE DATABASE sapieconf;'
    - php artisan key:generate
    - php artisan migrate:fresh --seed

script:
  - phpunit

branches:
  only:
    - master
    - dev
    - main
deploy:
  provider: heroku
  edge: true
  api_key: 39bdfede-b7e3-4546-a716-d38d91fcaf99
  app: allamvizsgafinal
  on:
    branch: main
