language: php

php:
  - 7.4

services:
  - mysql

before_script:
    - composer update
    - cp .env.example .env
    - mysql -e 'CREATE DATABASE sapieconf;'
    - php artisan key:generate
    - php artisan migrate:fresh --seed

script:
  - phpunit

branches:
  only:
    - master
    - dev
    - main