language: php

php:
  - 7.4

services:
  - mysql

before_script:
    - composer update
    - cp .env.example .env
    - mysql -e 'CREATE DATABASE sapieconf;'
    - php artisan key:generate
    - php artisan migrate:fresh --seed

script:
  - phpunit

branches:
  only:
    - master
    - dev
    - main
deploy:
  provider: heroku
  edge: true
  api_key: cf9a4546-58ca-41b8-9832-435a7547511f
  app: allamvizsgafinal
  on:
    branch: main
